### ISSUE TITLE
Example library of commonly used quantum devices and how to make them in metal with images and nbs [HIGH] [Epic]

### ISSUE THREAD

**Issue by zlatko-minev** [Qiskit/qiskit-metal#291]
Set up documentation to have example how-to create and analyze circuits as in qiskit

<img width="1920" alt="Screen Shot 2021-02-25 at 10 23 42 AM" src="https://user-images.githubusercontent.com/15937254/109361499-04073080-7857-11eb-8ca4-af6e89e8be34.png">

Update from discussions

Model after:
![image](https://user-images.githubusercontent.com/15937254/108291699-a2610b00-7160-11eb-9a71-08a6fcf5e348.png)

### What is the documentation modification?
Would be great to show this in APS MM
Would be great to scoping as part of MVP

# Circuit example library

The following is a placeholder outline

## Qubits
- [x] Single transmon - floating
- [x] Single transmon - grounded (xmon)
- [x] Concentric transmon  
- [ ] Placeholder: flux qubit 
- [ ] Placeholder fluxonium

## Resonators
- [x] Simple CPW meander
- [ ] Lumped resonator capacitive

## Composite bi-partite systems comprising qubit and resonator
- [x] Transmon coupled to CPW resonator 

## Qubit couplers 
- [x] Direct coupler (transmon-transmon)
- [x] Bus resonator coupler (transmon-transmon)
- [ ] Tunable g-mon (MIT)
- [ ] ...

## Input-output coupling
- [x] CPW launcher
- [x] Readout line 
- [x] Charge line

## Small quantum chips
 - [x] 4 qubit chip

## References to qiskit summer school in each notebook 
- [ ] Add reference to relevant video / lectures part (Lec 16-21) from qiskit summer school Introduction to Quantum Computing and Quantum Hardware  https://qiskit.org/learn/intro-qc-qh/ (ask Minev if needed for exact reference location)

Example thumbnail of a direct coupler for two transmon qubits
![image](https://user-images.githubusercontent.com/15937254/108293683-bc9be880-7162-11eb-8e7c-a1e829d54ca7.png)
